version: '3.4'

services:
  topic_query_app:
    container_name: iahx-topic-query
    restart: unless-stopped
    build:
      context: .
      target: prod
    image: ${IMAGE_TAG}
    volumes:
        - ${LOG_PATH}:/logs
        - static_files:/app/static_files
        - gunisock:/tmp
    env_file:
        - ./conf/app-env
    command: gunicorn --bind unix:/tmp/gunicorn.sock topic_query.wsgi ${COMMAND_PARAMS}
    networks:
      - nginx-proxy
    deploy:
      resources:
        limits:
          memory: ${MEMORY_APP_LIMIT}
        reservations:
          memory: ${MEMORY_APP_RESERVATION}

  topic_query_app_webserver:
    container_name: iahx-topic-query-webserver
    restart: unless-stopped
    image: nginx:1.20-alpine
    expose:
      - 80
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - static_files:/app/static_files
      - gunisock:/tmp
    depends_on:
      - topic_query_app
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    networks:
      - nginx-proxy
    deploy:
      resources:
        limits:
          memory: ${MEMORY_WEBSERVER_LIMIT}
        reservations:
          memory: ${MEMORY_WEBSERVER_RESERVATION}

networks:
  nginx-proxy:
    external: true

volumes:
  static_files:
  gunisock: